### ISSUE TITLE
Communicate with the device via the WebUSB API instead of extra software

### ISSUE THREAD

**Issue by hybridherbst** [Looking-Glass/looking-glass-webxr#24]
This is mostly an idea: the web USB API is now enabled by default in Chrome, and as far as I understand designed to allow communication with attached microcontrollers and such, so may be possible to talk to LG without even having to install the bridge.

**Comment by BryanChrisBrown** [comment]
While this is technically feasible it's not something we're planning on implementing. Currently Bridge provides calibration data, but as time goes on, we intend to include other functionality as well that users would want to access, including things like automatic window management and managing multiple devices.
