### ISSUE TITLE
Initial targetY not actually applied

### ISSUE THREAD

**Issue by JuanIrache** [Looking-Glass/looking-glass-webxr#4]
Hi. I might have found an issue. It seems the config.targetY initially set is not what is actually used when the code runs. See this example:

https://editor.p5js.org/JuanIrache/sketches/JH9XXXwCK
(I'm sharing it in the p5js editor because codesandbox is very unstable when running this, but you can try it thereif you prefer)
https://codesandbox.io/s/p5js-webxr-looking-glass-tfddd4

I'm importing the library as a tag in index.html and setting the config like in the provided examples, including.
`config.targetY = 0;
`
Then when run the page and enter VR, the cube is not centered but near the top margin. If you reset the targetY from the UI to be zero (it already looks like zero, but try it), the cube goes to the center as expected.

Edit: Interestingly, if you remove the **config.targetY = 0;** line entirely, the target is centered! (I will comment that line for now, uncomment it to reproduce the problem)

**Comment by BryanChrisBrown** [comment]
interesting, thanks for providing the link I'll take a look at it! It looks like this is only affecting the version available via the <script> tag for now, let me see what I can do about getting that in a proper release bundle.

**Comment by BryanChrisBrown** [comment]
This will be fixed in the next release of the library 👍🏻

**Comment by BryanChrisBrown** [comment]
This was fixed a while ago, forgot to close 😅
