### ISSUE TITLE
when I fullscreen the window, the animation will be paused

### ISSUE THREAD

**Issue by klren0312** [Looking-Glass/looking-glass-webxr#52]
![Kapture 2024-07-03 at 10 49 22](https://github.com/Looking-Glass/looking-glass-webxr/assets/10903843/4f74bded-7fa2-4220-b102-bfa8c226ca8a)

**Comment by BryanChrisBrown** [comment]
Looks like this is MacOS, this is because the full screen window is hiding the main window, causing it to no longer call requestAnimationFrame, 

If this is happening when you full screen the window on Looking Glass as well you may need to change your display settings to enable multiple workspaces.

**Comment by klren0312** [comment]
OK, thanks
